# Generated by Django 5.0.6 on 2024-05-16 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject', '0003_item_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='item',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangoProject.item'),
        ),
    ]
